# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install all dependencies (including dev for build)
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

# Copy source and compile
COPY src ./src
RUN npm run build

# production stage
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy built output
COPY --from=builder /app/build ./build

EXPOSE 8080
CMD ["node","build/index.js"]
